### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by pro-sumer** [fent/node-feedsub#53]
On feed http://tweakers.net/feeds/meuktracker.xml I got the error below (on 23-Sep-2020 11:56:15):

```
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:266:14)
    at PassThrough.Writable.write (_stream_writable.js:315:5)
    at Gunzip.ondata (_stream_readable.js:716:22)
    at Gunzip.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Gunzip.Readable.push (_stream_readable.js:212:10)
    at Gunzip.Transform.push (_stream_transform.js:152:32)
    at Zlib.processCallback (zlib.js:531:10)
Emitted 'error' event on FeedReader instance at:
    at error (/home/pi/test/node_modules/feedsub/lib/feedsub.js:121:16)
    at PassThrough.emit (events.js:327:22)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at writeAfterEnd (_stream_writable.js:268:3)
    at PassThrough.Writable.write (_stream_writable.js:315:5)
    [... lines matching original stack trace ...]
    at Gunzip.Readable.push (_stream_readable.js:212:10) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

**Comment by pro-sumer** [comment]
Happened again on 23-Sep-2020 21:32:54.

Unfortunately the log does not show for which feed entry, so I hope the timestamp helps in debugging.

**Comment by fent** [comment]
this may be caused by [miniget](https://github.com/fent/node-miniget), i've seen it before in another project that uses it. i'll have to investigate miniget's code.
